# Build artifacts
EmpathAPI/.gradle/
EmpathAPI/build/
EmpathAPI/bin/
qupath-extension-scriptlauncher/.gradle/
qupath-extension-scriptlauncher/build/
qupath-extension-scriptlauncher/bin/

# Git
**/.git/
**/.gitignore

# Exclude unrelated local repos
xopat/
EMPAIA-Workbench-Service/
